### ISSUE TITLE
qosify: Hangs after libbpf update to v1.1

### ISSUE THREAD

**Issue by Fail-Safe** [openwrt/qosify#1]
After the recent upgrade to `libbpf` v1.1, qosify hangs (and locks up a CPU core) when starting. Also raised the issue on the commit that introduced the `libbpf` update: https://github.com/openwrt/openwrt/commit/26a65e852c5bd8e586205ce8dff582de623cb566#commitcomment-103307777

Details of the issue and my configuration are here:
https://forum.openwrt.org/t/qosify-new-package-for-dscp-marking-cake/111789/1231?u=_failsafe
https://forum.openwrt.org/t/qosify-new-package-for-dscp-marking-cake/111789/1233?u=_failsafe

**Comment by nbd168** [comment]
Pushed a fix, please try the latest version.

**Comment by Fail-Safe** [comment]
Affirmative--back to working again with libbpf v1.1. Thank you so much for the quick fix!
